### ISSUE TITLE
Add functionality to alter cohort end date

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/CohortConstructor#78]

**Comment by catalamarti** [comment]
should we allow this functionality for cohort_start_date? I mean you may have a cohort that the cohort start date is when 1 of the 3 conditions are fulfilled, or the other way round, that it is when 3 conditions are fulfilled.
@edward-burn @nmercadeb

**Comment by nmercadeb** [comment]
I agree that it would be nice to have entryAtFrstDate and entryAtLastDate as well

**Comment by nmercadeb** [comment]
exitAtDeath
-> argument whether to drop people at death: requireDeath

**Comment by nmercadeb** [comment]
```
exitAtFirstDate(cohort,
                cohortId = NULL,
                outOfObservation = "drop",
                removeNA = FALSE,
                name = omopgenerics::tableName(cohort))
```

**outOfObservation:** Strategy to handle end dates outside observation period: "asis" to keep the original cohort end date, "drop" to drop those entries, and "end" to set cohort end at observation end date.
**removeNA:** If TRUE empty dates will not be used to compute the end date, but if FALSE cohort end date will be NA when one of the dates is empty.

**Comment by edward-burn** [comment]
For missing data, I wonder if we can base the arguments on https://www.rdocumentation.org/packages/xcms/versions/1.48.0/topics/colMax and pmax https://www.rdocumentation.org/packages/Rmpfr/versions/0.9-5/topics/pmax - i.e. have na.rm = TRUE/ FALSE (with similar behaviour - either ignore or return NA)

**Comment by edward-burn** [comment]
For outOfObservation, let me think a little and then lets discuss before releasing (but happy to incorporate a pr with the behaviour currently suggested!)

**Comment by nmercadeb** [comment]
```
exitAtFirstDate(cohort,
                dateColumns,
                cohortId = NULL,
                outOfObservation = "drop",
                exitReason= FALSE,
                name = omopgenerics::tableName(cohort))
```

Considerations and suggested behaviour:
- if new date out of observation, two possibilities set in `outOfObservation`: 1) "drop" those records, 2) "end" set observation period end date as new date
- empty dates: if some dates are empty they are not considered when calculating the minimum/maximum, if all dates are NA that record is dropped (empty end dates not allowed since then we cannot check for overlapping entries)
- new end < start --> drop
- overlapping entries --> erafy and set as exit reason the reason of the final end date (and maybe throw a warning/message?)
- if more than 1 date equal and fullfulling minimum/maximum --> in exit reason join column names ";"

**Comment by edward-burn** [comment]
Now all added thanks to @nmercadeb
